# STMap_BBox — smart auto-loader (generated by ndk_build package).
#
# Folder layout (MAJOR.MINOR dispatch — Foundry's NDK is not ABI-stable across
# minors, e.g. Nuke 16.0 vs 16.1, so we ship one binary per minor):
#   STMap_BBox/init.py            ← this file
#   STMap_BBox/menu.py
#   STMap_BBox/builds/Mac/Nuke<MAJOR>_<MINOR>/STMap_BBox.dylib
#   STMap_BBox/builds/Linux/Nuke<MAJOR>_<MINOR>/STMap_BBox.so
#   STMap_BBox/builds/Windows/Nuke<MAJOR>_<MINOR>/STMap_BBox.dll
#
# Lookup is exact-match on Nuke<MAJOR>_<MINOR>: the v-release patch number is
# deliberately not part of the folder name (only major+minor matter for ABI;
# release is a within-minor implementation detail). If the host's
# (major, minor) has no matching folder, the plugin is not loaded — print a
# warning via nuke.tprint and continue. Nuke startup is never blocked.

import os
import platform
import re

import nuke


_DEBUG = os.getenv("STMAP_BBOX_DEBUG_INIT") == "1"


def _tprint(message):
    try:
        nuke.tprint(message)
    except Exception:
        print(message)


def _platform_label():
    system = platform.system()
    if system == "Darwin":
        return "Mac"
    if system in ("Linux", "Windows"):
        return system
    return system or "UnknownOS"


def _binary_name(os_label):
    if os_label == "Mac":
        return "STMap_BBox.dylib"
    if os_label == "Linux":
        return "STMap_BBox.so"
    if os_label == "Windows":
        return "STMap_BBox.dll"
    return None


def _version_parts():
    major = getattr(nuke, "NUKE_VERSION_MAJOR", None)
    minor = getattr(nuke, "NUKE_VERSION_MINOR", None)
    version_string = getattr(nuke, "NUKE_VERSION_STRING", "")

    if (major is None or minor is None) and version_string:
        match = re.search(r"(\d+)\.(\d+)", str(version_string))
        if match:
            if major is None:
                major = int(match.group(1))
            if minor is None:
                minor = int(match.group(2))

    return major, minor


def _display_version(major, minor):
    if major is None or minor is None:
        return "unknown Nuke version"
    return "Nuke %s.%s" % (major, minor)


def _version_label(major, minor):
    if major is None or minor is None:
        return None
    return "Nuke%s_%s" % (major, minor)


def _plugin_path():
    package_dir = os.path.dirname(os.path.abspath(__file__))
    os_label = _platform_label()
    binary = _binary_name(os_label)
    major, minor = _version_parts()
    display_version = _display_version(major, minor)

    if not binary:
        return None, "STMap_BBox: No build available for %s %s. Plugin not loaded." % (
            os_label,
            display_version,
        )

    label = _version_label(major, minor)
    if label is None:
        return None, "STMap_BBox: Could not resolve Nuke (major, minor); plugin not loaded."

    candidate = os.path.join(package_dir, "builds", os_label, label)
    if os.path.isfile(os.path.join(candidate, binary)):
        return candidate, None

    return None, "STMap_BBox: No build available for %s %s. Plugin not loaded." % (
        os_label,
        display_version,
    )


def load_stmap_bbox():
    plugin_path, error_message = _plugin_path()
    if plugin_path:
        if _DEBUG:
            _tprint("STMap_BBox: adding plugin path %s" % plugin_path)
        nuke.pluginAddPath(plugin_path)
        try:
            nuke.load("STMap_BBox")
        except RuntimeError as error:
            _tprint("STMap_BBox: Failed to load plugin - %s" % error)
    else:
        _tprint(error_message)


load_stmap_bbox()
