# STMap_BBox — Nuke menu placement (generated by ndk_build package).
#
# init.py loaded the plugin and added its folder to the plugin path. Here we
# attach the node to the Nodes menu so users can find it via Tab → name or by
# clicking the menu entry.

import nuke


def _register():
    toolbar = nuke.menu("Nodes")
    submenu = toolbar.addMenu("Transform")
    submenu.addCommand(
        "STMap_BBox",
        "nuke.createNode('STMap_BBox')",
    )


_register()
